### ISSUE TITLE
Internal Server Error 500 when clicking on "Envelope Budget" in navigation bar

### ISSUE THREAD

**Issue by ghudspeth** [polarmutex/fava-envelope#38]
Receive the following error:

Exception on /beancount/extension/EnvelopeBudget/ [GET]
Traceback (most recent call last):
  File "/home/glenn/finances/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/glenn/finances/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/glenn/finances/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/glenn/finances/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/glenn/finances/venv/lib/python3.8/site-packages/fava/application.py", line 352, in extension_report
    content = render_template_string(template, extension=extension)
  File "/home/glenn/finances/venv/lib/python3.8/site-packages/flask/templating.py", line 165, in render_template_string
    return _render(ctx.app.jinja_env.from_string(source), context, ctx.app)
  File "/home/glenn/finances/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/glenn/finances/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/glenn/finances/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 25, in top-level template code
  File "/home/glenn/finances/venv/lib/python3.8/site-packages/jinja2/utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'url_for_current' is undefined

**Comment by egetzner** [comment]
Seems familiar and should be fixed already in PR #33 . Which version are you running? Maybe try installing from git directly:  `pip install git+https://github.com/polarmutex/fava-envelope.git` ?

**Comment by ghudspeth** [comment]
> Seems familiar and should be fixed already in PR #33 . Which version are you running? Maybe try installing from git directly: `pip install git+https://github.com/polarmutex/fava-envelope.git` ?

I'm sorry to report this didn't help. I even ended up reinstalling Ubuntu 20.04 under WSL2 and re-cloning my app from Github to see if that would clear up any weirdness.

**Comment by Mounica134** [comment]
I recently installed fava-envelope and I have the same issue. I am running windows 10

**Comment by yuvipanda** [comment]
I just tried installing from master, yet get the same error.

**Comment by yuvipanda** [comment]
Nevermind, I uninstalled and then installed from master with ` pip install -f -U git+https://github.com/polarmutex/fava-envelope@master` and that worked. Needs a release on PyPI I guess.

Thank you for this cool extension!

**Comment by ludaavics** [comment]
@polarmutex any chance for a new release on pypi for this? Thanks!

**Comment by polarmutex** [comment]
I will try here soon, been really busy

**Comment by polarmutex** [comment]
released publish, I plan to give this more love, let me know of any improvements you can think of
